version: "3.8"

services:
  speciesnet-app:
    image: my-speciesnet
    container_name: speciesnet-container
    ports:
      - "12345:80"
    volumes:
      - ./image:/app/image
      - ./output:/app/output
      - ./cropped_images:/app/cropped_images
    restart: unless-stopped
    command: ["python", "-m", "http.server", "80", "--directory", "/app"]
